import type { Metadata } from "next";
import "@/styles/globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Readum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[800px] mx-auto">
        <Header />

        <main>{children}</main>
      </body>
    </html>
  );
}
