version: "3.9"

services:
  backend:
    container_name: readum-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: developer
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
      - PORT=8080
    networks:
      - readum-network
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    container_name: readum-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: developer
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=3000
    networks:
      - readum-network
    depends_on:
      - backend

networks:
  readum-network:
