version: "3.9"

services:
  backend:
    container_name: readum-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
      - PORT=8080
    networks:
      - readum-network

  frontend:
    container_name: readum-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - readum-network
    depends_on:
      - backend

networks:
  readum-network:
