name: Deploy Backend to Cloud Run (STG)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-stg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up GCP authentication
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      # JSON KEYを使用した認証
      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_DEPLOY_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ vars.GCP_PROJECT_ID }}
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
          rm gcp-key.json

      - name: Build and push Docker image
        working-directory: backend
        run: |
          docker build --platform linux/amd64 -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/readum-repo/readum-backend:${{ github.sha }} -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/readum-repo/readum-backend:latest .

          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/readum-repo/readum-backend:${{ github.sha }}
          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/readum-repo/readum-backend:latest

      - name: Deploy to Cloud Run
        env:
          tag_name: stg
        run: |
          gcloud run services update readum-backend \
            --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/readum-repo/readum-backend:${{ github.sha }} \
            --region ${{ vars.GCP_REGION }} \
            --tag ${{ env.tag_name }} \
            --update-env-vars ALLOW_ORIGIN=https://${{ env.tag_name }}---${{ vars.ALLOW_ORIGIN }} \
            --no-traffic
